import Foundation
import AppKit
import ApplicationServices
import Carbon.HIToolbox
import os
import os.log

private let logger = Logger(subsystem: Bundle.main.bundleIdentifier ?? "Leise", category: "TextInsertionService")

/// Inserts transcribed text into the active application via clipboard + simulated Cmd+V.
@MainActor
final class TextInsertionService {
    private let syntheticPastePreferredBundleIdentifiers: Set<String> = [
        "com.apple.Terminal",
        "com.googlecode.iterm2",
        "com.github.wez.wezterm",
        "dev.warp.Warp",
        "dev.warp.Warp-Stable",
        "dev.warp.Warp-Preview",
        "dev.warp.WarpPreview",
        "com.mitchellh.ghostty"
    ]
    private let generatedPasteboardMarkerTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.leise.SpeechTranscription")
    ]

    typealias FocusedTextSnapshot = (value: String?, selectedText: String?, selectedRange: NSRange?)

    var accessibilityGrantedOverride: Bool?
    var pasteboardProvider: () -> NSPasteboard = { .general }
    var focusedTextFieldOverride: (() -> Bool)?
    var focusedTextElementOverride: (() -> AXUIElement?)?
    var focusedTextStateOverride: ((AXUIElement) -> FocusedTextSnapshot?)?
    var textSelectionOverride: (() -> TextSelection?)?
    var insertTextAtOverride: ((AXUIElement, String) -> Bool)?
    var pasteSimulatorOverride: (() -> Void)?
    var returnSimulatorOverride: (() -> Void)?
    var captureActiveAppOverride: (() -> (name: String?, bundleId: String?, url: String?))?
    var selectedTextOverride: (() -> String?)?
    var pasteVerificationAttempts = 10
    var pasteVerificationPollingDelay: Duration = .milliseconds(50)
    var defaultPasteFallbackRestoreDelay: Duration = .milliseconds(350)
    var richTextPasteFallbackRestoreDelay: Duration = .milliseconds(1500)
    var terminalPasteFallbackRestoreDelay: Duration = .milliseconds(900)
    var verifiedRestoreGraceDelay: Duration = .milliseconds(150)

    enum InsertionResult: Equatable {
        case insertedViaAccessibility
        case pasted(verification: PasteVerification)
    }

    enum PasteVerification: Equatable {
        case verified
        case unverified(PasteVerificationFailure)
    }

    enum PasteVerificationFailure: String, Equatable {
        case focusedTextStateUnavailable = "focused-text-state-unavailable"
        case focusedTextUnchanged = "focused-text-unchanged"
    }

    enum TextInsertionError: LocalizedError {
        case accessibilityNotGranted
        case pasteFailed(String)

        var errorDescription: String? {
            switch self {
            case .accessibilityNotGranted:
                "Accessibility permission not granted. Please enable it in System Settings → Privacy & Security → Accessibility."
            case .pasteFailed(let detail):
                "Failed to paste text: \(detail)"
            }
        }
    }

    var isAccessibilityGranted: Bool {
        accessibilityGrantedOverride ?? AXIsProcessTrusted()
    }

    func requestAccessibilityPermission() {
        // Try the prompt first
        let options = ["AXTrustedCheckOptionPrompt" as CFString: true] as CFDictionary
        AXIsProcessTrustedWithOptions(options)

        // Also open System Settings directly (prompt alone may not work in sandbox)
        if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility") {
            NSWorkspace.shared.open(url)
        }
    }

    func captureActiveApp() -> (name: String?, bundleId: String?, url: String?) {
        if let captureActiveAppOverride {
            return captureActiveAppOverride()
        }
        let app = NSWorkspace.shared.frontmostApplication
        let bundleId = app?.bundleIdentifier
        return (app?.localizedName, bundleId, nil)
    }

    func resolveBrowserURL(bundleId: String) async -> String? {
        await Self.getBrowserURL(bundleId: bundleId)
    }

    // MARK: - Browser URL Detection

    private enum BrowserType: String {
        case safari, arc, chromiumBased, firefox, notABrowser
    }

    nonisolated private static func identifyBrowser(_ bundleId: String) -> BrowserType {
        let normalized = bundleId.lowercased()
        if normalized.contains("wavebox") {
            return .chromiumBased
        }

        switch bundleId {
        case "com.apple.Safari":
            return .safari
        case "company.thebrowser.Browser":
            return .arc
        case "com.google.Chrome",
             "com.google.Chrome.canary",
             "com.brave.Browser",
             "com.microsoft.edgemac",
             "com.operasoftware.Opera",
             "com.vivaldi.Vivaldi",
             "org.chromium.Chromium":
            return .chromiumBased
        case "org.mozilla.firefox":
            return .firefox
        default:
            return .notABrowser
        }
    }

    nonisolated private static func getBrowserURL(bundleId: String) async -> String? {
        let browserType = identifyBrowser(bundleId)
        guard browserType != .notABrowser else { return nil }

        // Firefox doesn't support AppleScript for URL access
        guard browserType != .firefox else { return nil }

        // Resolve app name for AppleScript (required in sandbox - "tell application id" doesn't work)
        let appName = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleId)
            .flatMap { Bundle(url: $0)?.infoDictionary?["CFBundleName"] as? String }
            ?? bundleId


        let script: String
        switch browserType {
        case .safari:
            script = """
            tell application "\(appName)"
                if (count of windows) > 0 then
                    return URL of current tab of front window
                end if
            end tell
            return ""
            """
        case .arc, .chromiumBased:
            script = """
            tell application "\(appName)"
                if (count of windows) > 0 then
                    return URL of active tab of front window
                end if
            end tell
            return ""
            """
        default:
            return nil
        }

        return await executeAppleScript(script, timeout: 2.5)
    }

    /// Runs the script on a global queue and suspends instead of blocking a
    /// cooperative-pool thread on a semaphore; the continuation is resumed by
    /// whichever of completion or timeout comes first.
    nonisolated private static func executeAppleScript(_ source: String, timeout: TimeInterval, validateURL: Bool = true) async -> String? {
        let result: String? = await withCheckedContinuation { continuation in
            let hasResumed = OSAllocatedUnfairLock(initialState: false)
            let resumeOnce: (String?) -> Bool = { value in
                let shouldResume = hasResumed.withLock { resumed -> Bool in
                    guard !resumed else { return false }
                    resumed = true
                    return true
                }
                if shouldResume {
                    continuation.resume(returning: value)
                }
                return shouldResume
            }

            DispatchQueue.global(qos: .userInitiated).async {
                var error: NSDictionary?
                let script = NSAppleScript(source: source)
                let descriptor = script?.executeAndReturnError(&error)
                if let errorDict = error {
                    logger.warning("NSAppleScript error: \(errorDict)")
                }
                _ = resumeOnce(descriptor?.stringValue)
            }

            DispatchQueue.global(qos: .userInitiated).asyncAfter(deadline: .now() + timeout) {
                if resumeOnce(nil) {
                    logger.warning("NSAppleScript timed out after \(timeout)s")
                }
            }
        }

        guard let result, !result.isEmpty else { return nil }
        if validateURL {
            guard isValidURL(result) else { return nil }
        }
        return result
    }

    nonisolated private static func isValidURL(_ string: String) -> Bool {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count > 3, trimmed.count < 2048 else { return false }
        return trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://") || trimmed.hasPrefix("file://")
    }

    /// Captures the selected text and the AXUIElement it belongs to.
    struct TextSelection: @unchecked Sendable {
        let text: String
        let element: AXUIElement
    }

    struct InsertionContext: Equatable {
        let value: String
        let selectedRange: NSRange
        let selectedText: String?
        let previousCharacter: Character?
        let nextCharacter: Character?
    }

    typealias ClipboardItemSnapshot = [NSPasteboard.PasteboardType: Data]
    typealias ClipboardSnapshot = [ClipboardItemSnapshot]

    struct PasteVerificationState {
        fileprivate let focusedTextState: FocusedTextState?
    }

    fileprivate struct FocusedTextState: Equatable {
        let element: AXUIElement
        let value: String?
        let selectedText: String?
        let selectedRange: NSRange?

        static func == (lhs: FocusedTextState, rhs: FocusedTextState) -> Bool {
            lhs.element == rhs.element &&
            lhs.value == rhs.value &&
            lhs.selectedText == rhs.selectedText &&
            lhs.selectedRange == rhs.selectedRange
        }
    }

    func getSelectedText() -> String? {
        if let selectedTextOverride {
            return selectedTextOverride()
        }
        return getTextSelection()?.text
    }

    /// Returns the selected text and the AXUIElement, so the selection can be replaced later.
    func getTextSelection() -> TextSelection? {
        if let textSelectionOverride {
            return textSelectionOverride()
        }
        guard isAccessibilityGranted else { return nil }

        let element: AXUIElement
        if let focusedTextElementOverride {
            guard let overrideElement = focusedTextElementOverride() else { return nil }
            element = overrideElement
        } else {
            let systemWide = AXUIElementCreateSystemWide()
            var focusedElement: AnyObject?
            guard AXUIElementCopyAttributeValue(
                systemWide,
                kAXFocusedUIElementAttribute as CFString,
                &focusedElement
            ) == .success else {
                return nil
            }
            guard let focusedElement,
                  CFGetTypeID(focusedElement) == AXUIElementGetTypeID() else {
                return nil
            }
            element = focusedElement as! AXUIElement
        }

        if let selection = selectionOwnedByElement(element) {
            return selection
        }
        return findSelectionInDescendants(of: element)
    }

    /// Returns the focused text element (even without selection), for later insertion.
    func getFocusedTextElement() -> AXUIElement? {
        if let focusedTextElementOverride {
            return focusedTextElementOverride()
        }
        guard isAccessibilityGranted else { return nil }

        let systemWide = AXUIElementCreateSystemWide()
        var focusedElement: AnyObject?
        guard AXUIElementCopyAttributeValue(systemWide, kAXFocusedUIElementAttribute as CFString, &focusedElement) == .success else {
            return nil
        }
        guard let focusedElement,
              CFGetTypeID(focusedElement) == AXUIElementGetTypeID() else {
            return nil
        }

        let element = focusedElement as! AXUIElement
        var roleValue: AnyObject?
        guard AXUIElementCopyAttributeValue(element, kAXRoleAttribute as CFString, &roleValue) == .success,
              let role = roleValue as? String else { return nil }

        let textRoles = ["AXTextField", "AXTextArea", "AXComboBox", "AXSearchField", "AXWebArea"]
        guard textRoles.contains(role) else { return nil }
        return element
    }

    /// Inserts text at the cursor position of a previously captured AXUIElement.
    func insertTextAt(element: AXUIElement, text: String) -> Bool {
        if let insertTextAtOverride {
            return insertTextAtOverride(element, text)
        }

        let result = AXUIElementSetAttributeValue(
            element,
            kAXSelectedTextAttribute as CFString,
            text as CFTypeRef
        )
        return result == .success
    }

    /// Inserts via Accessibility only when we can verify that the focused text state changed.
    /// This avoids silently dropping text in apps that report AX success but ignore the write.
    func insertTextAtAndVerifyChange(element: AXUIElement, text: String) -> Bool {
        guard let initialState = captureFocusedTextState(for: element) else {
            return false
        }
        guard insertTextAt(element: element, text: text),
              let currentState = captureFocusedTextState(for: element) else {
            return false
        }
        guard let currentValue = currentState.value else {
            return false
        }
        // Replacing a selection with identical text leaves the value unchanged, so
        // compare against the expected post-insertion value before requiring a change.
        if let initialValue = initialState.value,
           let selectedRange = initialState.selectedRange,
           let replacementRange = Range(selectedRange, in: initialValue) {
            let expectedValue = initialValue.replacingCharacters(in: replacementRange, with: text)
            if currentValue == expectedValue {
                return true
            }
        }
        return initialState.value != currentValue
    }

    /// Saves all current clipboard contents for later restoration.
    func saveClipboard(from pasteboard: NSPasteboard = .general) -> ClipboardSnapshot {
        Self.clipboardSnapshot(from: pasteboard.pasteboardItems ?? [])
    }

    /// Restores previously saved clipboard contents.
    func restoreClipboard(_ savedItems: ClipboardSnapshot, to pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        if !savedItems.isEmpty {
            pasteboard.writeObjects(Self.pasteboardItems(from: savedItems))
        }
    }

    func capturePasteVerificationState() -> PasteVerificationState {
        PasteVerificationState(focusedTextState: captureFocusedTextState())
    }

    func captureInsertionContext() -> InsertionContext? {
        guard let state = captureFocusedTextState(),
              let value = state.value,
              let selectedRange = state.selectedRange,
              let stringRange = Range(selectedRange, in: value) else {
            return nil
        }

        let previousCharacter = stringRange.lowerBound > value.startIndex
            ? value[value.index(before: stringRange.lowerBound)]
            : nil
        let nextCharacter = stringRange.upperBound < value.endIndex
            ? value[stringRange.upperBound]
            : nil

        return InsertionContext(
            value: value,
            selectedRange: selectedRange,
            selectedText: state.selectedText,
            previousCharacter: previousCharacter,
            nextCharacter: nextCharacter
        )
    }

    func canRestoreClipboard(afterPasteUsing state: PasteVerificationState) -> Bool {
        guard let initialState = state.focusedTextState,
              let currentState = captureFocusedTextState(for: initialState.element) else {
            return false
        }
        return Self.focusedTextDidChange(
            from: (
                value: initialState.value,
                selectedText: initialState.selectedText,
                selectedRange: initialState.selectedRange
            ),
            to: (
                value: currentState.value,
                selectedText: currentState.selectedText,
                selectedRange: currentState.selectedRange
            )
        )
    }

    func insertText(
        _ text: String,
        preserveClipboard: Bool = false,
        autoEnter: Bool = false,
        outputFormat: String? = nil
    ) async throws -> InsertionResult {
        guard isAccessibilityGranted else {
            throw TextInsertionError.accessibilityNotGranted
        }

        let hadFocusedTextField = autoEnter && hasFocusedTextField()
        let formattedClipboardPayload = ClipboardContentFormatter.payload(for: text, outputFormat: outputFormat)
        let requiresPasteboardInsertion = ClipboardContentFormatter.requiresPasteboardInsertion(
            outputFormat: outputFormat
        )
        let activeApp = captureActiveApp()
        let appName = activeApp.name
        let bundleId = activeApp.bundleId
        let isTerminalApp = bundleId.map { syntheticPastePreferredBundleIdentifiers.contains($0) } ?? false

        logger.info(
            "insertText requested: app=\(appName ?? "nil", privacy: .public), bundle=\(bundleId ?? "nil", privacy: .public), preserveClipboard=\(preserveClipboard, privacy: .public), outputFormat=\(outputFormat ?? "plain", privacy: .public), terminalPreferredSyntheticPaste=\(isTerminalApp, privacy: .public)"
        )

        if preserveClipboard, !requiresPasteboardInsertion, !isTerminalApp,
           let focusedElement = getFocusedTextElement(),
           insertTextAtAndVerifyChange(element: focusedElement, text: text) {
            if hadFocusedTextField {
                try? await Task.sleep(for: .milliseconds(50))
                simulateReturn()
            }
            logger.info(
                "insertText completed via verified AX insertion: bundle=\(bundleId ?? "nil", privacy: .public)"
            )
            return .insertedViaAccessibility
        }

        let pasteboard = pasteboardProvider()
        let savedItems = preserveClipboard
            ? saveClipboard(from: pasteboard)
            : []
        let pasteVerificationState = capturePasteVerificationState()
        let initialChangeCount = pasteboard.changeCount

        // Set transcribed text on clipboard and simulate Cmd+V.
        // Text stays on clipboard as fallback if no text field is focused.
        pasteboard.clearContents()
        let generatedPayload = formattedClipboardPayload ?? ClipboardContentPayload(plainText: text)
        generatedPayload.write(to: pasteboard, markerTypes: generatedPasteboardMarkerTypes)
        logger.info(
            "insertText using synthetic paste: bundle=\(bundleId ?? "nil", privacy: .public), preserveClipboard=\(preserveClipboard, privacy: .public), changeCountBefore=\(initialChangeCount, privacy: .public), changeCountAfterWrite=\(pasteboard.changeCount, privacy: .public)"
        )
        simulatePaste()

        let verification = await waitForPasteVerification(using: pasteVerificationState)
        logPasteVerification(verification, bundleId: bundleId)

        if preserveClipboard {
            if verification == .unverified(.focusedTextUnchanged) {
                // The focused text field observably did not change, so the paste failed.
                // Keep the dictated text on the clipboard instead of restoring, so the
                // user can paste it manually — otherwise the text would be lost entirely.
                logger.warning(
                    "insertText skipping clipboard restore after failed paste; keeping dictated text on clipboard: bundle=\(bundleId ?? "nil", privacy: .public)"
                )
            } else {
                let restoreDelay: Duration
                if isTerminalApp {
                    restoreDelay = terminalPasteFallbackRestoreDelay
                } else if verification == .verified {
                    restoreDelay = verifiedRestoreGraceDelay
                } else if requiresPasteboardInsertion {
                    restoreDelay = richTextPasteFallbackRestoreDelay
                } else {
                    restoreDelay = defaultPasteFallbackRestoreDelay
                }

                if verification != .verified {
                    logger.warning(
                        "insertText delaying clipboard restore after unverified paste: bundle=\(bundleId ?? "nil", privacy: .public), delay=\(String(describing: restoreDelay), privacy: .public)"
                    )
                }
                try? await Task.sleep(for: restoreDelay)
                restoreClipboard(savedItems, to: pasteboard)
                logger.info(
                    "insertText restored clipboard: bundle=\(bundleId ?? "nil", privacy: .public), changeCountAfterRestore=\(pasteboard.changeCount, privacy: .public)"
                )
            }
        }

        if hadFocusedTextField {
            try? await Task.sleep(for: .milliseconds(50))
            simulateReturn()
        }

        return .pasted(verification: verification)
    }

    private func waitForPasteVerification(using state: PasteVerificationState) async -> PasteVerification {
        guard state.focusedTextState != nil else {
            return .unverified(.focusedTextStateUnavailable)
        }

        let attempts = max(0, pasteVerificationAttempts)
        for attempt in 0...attempts {
            if canRestoreClipboard(afterPasteUsing: state) {
                return .verified
            }
            guard attempt < attempts else { break }
            try? await Task.sleep(for: pasteVerificationPollingDelay)
        }

        return canRestoreClipboard(afterPasteUsing: state)
            ? .verified
            : .unverified(.focusedTextUnchanged)
    }

    private func logPasteVerification(_ verification: PasteVerification, bundleId: String?) {
        switch verification {
        case .verified:
            logger.info("insertText paste verified: bundle=\(bundleId ?? "nil", privacy: .public)")
        case .unverified(let reason):
            logger.info(
                "insertText paste unverified: bundle=\(bundleId ?? "nil", privacy: .public), reason=\(reason.rawValue, privacy: .public)"
            )
        }
    }

    func focusedElementPosition() -> CGPoint? {
        let systemWide = AXUIElementCreateSystemWide()

        var focusedElement: AnyObject?
        let result = AXUIElementCopyAttributeValue(systemWide, kAXFocusedUIElementAttribute as CFString, &focusedElement)
        guard result == .success, let element = focusedElement,
              CFGetTypeID(element) == AXUIElementGetTypeID() else {
            return nil
        }

        let axElement = element as! AXUIElement

        // Try to get the caret position from selected text range
        if let rect = caretRect(from: axElement) {
            return CGPoint(x: rect.origin.x + rect.width, y: rect.origin.y + rect.height)
        }

        // Fallback: get position of focused element
        return elementPosition(from: axElement)
    }

    /// Checks if the currently focused UI element is a text input field.
    func hasFocusedTextField() -> Bool {
        if let focusedTextFieldOverride {
            return focusedTextFieldOverride()
        }
        guard isAccessibilityGranted else { return false }

        let systemWide = AXUIElementCreateSystemWide()
        var focusedElement: AnyObject?
        let result = AXUIElementCopyAttributeValue(systemWide, kAXFocusedUIElementAttribute as CFString, &focusedElement)
        guard result == .success, let element = focusedElement,
              CFGetTypeID(element) == AXUIElementGetTypeID() else { return false }

        let axElement = element as! AXUIElement
        var roleValue: AnyObject?
        let roleResult = AXUIElementCopyAttributeValue(axElement, kAXRoleAttribute as CFString, &roleValue)
        guard roleResult == .success, let role = roleValue as? String else { return false }

        let textRoles = ["AXTextField", "AXTextArea", "AXComboBox", "AXSearchField", "AXWebArea"]
        return textRoles.contains(role)
    }

    private func caretRect(from element: AXUIElement) -> CGRect? {
        var selectedRangeValue: AnyObject?
        let rangeResult = AXUIElementCopyAttributeValue(
            element, kAXSelectedTextRangeAttribute as CFString, &selectedRangeValue
        )
        guard rangeResult == .success, let rangeValue = selectedRangeValue else { return nil }

        var bounds: CFTypeRef?
        let boundsResult = AXUIElementCopyParameterizedAttributeValue(
            element, kAXBoundsForRangeParameterizedAttribute as CFString, rangeValue, &bounds
        )
        guard boundsResult == .success, let boundsValue = bounds,
              CFGetTypeID(boundsValue) == AXValueGetTypeID() else { return nil }

        var rect = CGRect.zero
        guard AXValueGetValue(boundsValue as! AXValue, .cgRect, &rect) else { return nil }
        return rect
    }

    private func elementPosition(from element: AXUIElement) -> CGPoint? {
        var positionValue: AnyObject?
        let posResult = AXUIElementCopyAttributeValue(
            element, kAXPositionAttribute as CFString, &positionValue
        )
        guard posResult == .success, let posValue = positionValue else { return nil }

        var point = CGPoint.zero
        guard AXValueGetValue(posValue as! AXValue, .cgPoint, &point) else { return nil }
        return point
    }

    func simulateReturn() {
        if let returnSimulatorOverride {
            returnSimulatorOverride()
            return
        }
        let returnKeyCode: CGKeyCode = 0x24
        let keyDown = CGEvent(keyboardEventSource: nil, virtualKey: returnKeyCode, keyDown: true)
        keyDown?.flags = []
        keyDown?.post(tap: .cgSessionEventTap)

        let keyUp = CGEvent(keyboardEventSource: nil, virtualKey: returnKeyCode, keyDown: false)
        keyUp?.flags = []
        keyUp?.post(tap: .cgSessionEventTap)
    }

    private func simulatePaste() {
        if let pasteSimulatorOverride {
            pasteSimulatorOverride()
            return
        }
        let vKeyCode = virtualKeyCode(for: "v") ?? 0x09 // Fallback to QWERTY
        // Use nil source + .cgSessionEventTap for App Sandbox compatibility
        let keyDown = CGEvent(keyboardEventSource: nil, virtualKey: vKeyCode, keyDown: true)
        keyDown?.flags = .maskCommand
        keyDown?.post(tap: .cgSessionEventTap)

        let keyUp = CGEvent(keyboardEventSource: nil, virtualKey: vKeyCode, keyDown: false)
        keyUp?.flags = .maskCommand
        keyUp?.post(tap: .cgSessionEventTap)
    }

    /// Resolves the virtual key code for a character in the current keyboard layout.
    /// Uses Carbon HIToolbox APIs to scan all key codes and match against the layout.
    private func virtualKeyCode(for character: String) -> CGKeyCode? {
        let source = TISCopyCurrentKeyboardInputSource().takeRetainedValue()
        guard let layoutDataRef = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
            return nil
        }
        let layoutData = unsafeBitCast(layoutDataRef, to: CFData.self)
        let keyLayoutPtr = unsafeBitCast(CFDataGetBytePtr(layoutData), to: UnsafePointer<UCKeyboardLayout>.self)

        var deadKeyState: UInt32 = 0
        var chars = [UniChar](repeating: 0, count: 4)
        var length = 0

        for keyCode: UInt16 in 0...127 {
            deadKeyState = 0
            let status = UCKeyTranslate(
                keyLayoutPtr,
                keyCode,
                UInt16(kUCKeyActionDown),
                0, // no modifiers
                UInt32(LMGetKbdType()),
                UInt32(kUCKeyTranslateNoDeadKeysMask),
                &deadKeyState,
                chars.count,
                &length,
                &chars
            )
            if status == noErr && length > 0 {
                let s = String(utf16CodeUnits: chars, count: length)
                if s == character {
                    return CGKeyCode(keyCode)
                }
            }
        }
        return nil
    }

    static func clipboardSnapshot(from items: [NSPasteboardItem]) -> ClipboardSnapshot {
        items.map { item in
            Dictionary(uniqueKeysWithValues: item.types.compactMap { type in
                guard let data = item.data(forType: type) else { return nil }
                return (type, data)
            })
        }
    }

    static func pasteboardItems(from snapshot: ClipboardSnapshot) -> [NSPasteboardItem] {
        snapshot.map { itemSnapshot in
            let item = NSPasteboardItem()
            for (type, data) in itemSnapshot {
                item.setData(data, forType: type)
            }
            return item
        }
    }

    static func focusedTextDidChange(
        from initialState: (value: String?, selectedText: String?, selectedRange: NSRange?),
        to currentState: (value: String?, selectedText: String?, selectedRange: NSRange?)
    ) -> Bool {
        initialState.value != currentState.value ||
        initialState.selectedText != currentState.selectedText ||
        initialState.selectedRange != currentState.selectedRange
    }

    private func selectionOwnedByElement(_ element: AXUIElement) -> TextSelection? {
        var selectedText: AnyObject?
        let selectedTextResult = AXUIElementCopyAttributeValue(
            element,
            kAXSelectedTextAttribute as CFString,
            &selectedText
        )
        if selectedTextResult == .success,
           let text = selectedText as? String,
           !text.isEmpty {
            return TextSelection(text: text, element: element)
        }

        guard let text = selectedTextFromFocusedState(for: element) else {
            return nil
        }
        return TextSelection(text: text, element: element)
    }

    private func findSelectionInDescendants(of root: AXUIElement) -> TextSelection? {
        findSelectionInDescendants(of: root, maxDepth: 6, maxNodes: 80)
    }

    private func findSelectionInDescendants(
        of root: AXUIElement,
        maxDepth: Int,
        maxNodes: Int
    ) -> TextSelection? {
        var queue: [(element: AXUIElement, depth: Int)] = childElements(of: root).map { ($0, 1) }
        var visited = 0

        while !queue.isEmpty && visited < maxNodes {
            let current = queue.removeFirst()
            visited += 1

            if let selection = selectionOwnedByElement(current.element) {
                return selection
            }

            if current.depth < maxDepth {
                queue.append(contentsOf: childElements(of: current.element).map { ($0, current.depth + 1) })
            }
        }

        return nil
    }

    private func childElements(of element: AXUIElement) -> [AXUIElement] {
        var children: [AXUIElement] = []
        for attribute in [
            kAXChildrenAttribute as CFString,
            kAXContentsAttribute as CFString,
            "AXVisibleChildren" as CFString
        ] {
            var value: AnyObject?
            guard AXUIElementCopyAttributeValue(element, attribute, &value) == .success else {
                continue
            }

            if let child = axElement(from: value) {
                children.append(child)
            } else if let childArray = value as? [AXUIElement] {
                children.append(contentsOf: childArray)
            } else if let objectArray = value as? [AnyObject] {
                children.append(contentsOf: objectArray.compactMap { axElement(from: $0) })
            }
        }
        return children
    }

    private func axElement(from value: AnyObject?) -> AXUIElement? {
        guard let value,
              CFGetTypeID(value) == AXUIElementGetTypeID() else {
            return nil
        }
        return (value as! AXUIElement)
    }

    private func selectedTextFromFocusedState(for element: AXUIElement) -> String? {
        if let selectedRangesText = selectedTextFromSelectedTextRangesAttribute(for: element) {
            return selectedRangesText
        }

        var selectedRangeValue: AnyObject?
        let selectedRangeResult = AXUIElementCopyAttributeValue(
            element,
            kAXSelectedTextRangeAttribute as CFString,
            &selectedRangeValue
        )
        if selectedRangeResult == .success,
           let selectedRangeValue,
           let selectedRangeText = selectedText(from: selectedRangeValue, for: element) {
            return selectedRangeText
        }

        guard let state = captureFocusedTextState(for: element),
              let selectedRange = state.selectedRange else {
            return nil
        }

        return selectedText(from: selectedRange, value: state.value)
    }

    private func selectedTextFromSelectedTextRangesAttribute(for element: AXUIElement) -> String? {
        var selectedRangesValue: AnyObject?
        let selectedRangesResult = AXUIElementCopyAttributeValue(
            element,
            kAXSelectedTextRangesAttribute as CFString,
            &selectedRangesValue
        )
        let selectedRanges = selectedRangesValue as? [AnyObject]
        guard selectedRangesResult == .success,
              let selectedRanges,
              !selectedRanges.isEmpty else {
            return nil
        }

        let fragments = selectedRanges.compactMap { selectedText(from: $0, for: element) }
        guard !fragments.isEmpty else { return nil }
        return fragments.joined(separator: "\n")
    }

    private func selectedText(from rangeValue: AnyObject, for element: AXUIElement) -> String? {
        if let parameterizedText = stringForRange(rangeValue, from: element) {
            return parameterizedText
        }

        guard let range = nsRange(from: rangeValue),
              let value = stringAttribute(kAXValueAttribute as CFString, from: element) else {
            return nil
        }

        return selectedText(from: range, value: value)
    }

    private func stringForRange(_ rangeValue: AnyObject, from element: AXUIElement) -> String? {
        var textValue: AnyObject?
        let stringForRangeResult = AXUIElementCopyParameterizedAttributeValue(
            element,
            kAXStringForRangeParameterizedAttribute as CFString,
            rangeValue,
            &textValue
        )
        let text = textValue as? String
        guard stringForRangeResult == .success,
              let text,
              !text.isEmpty else {
            return nil
        }

        return text
    }

    private func selectedText(from range: NSRange, value: String?) -> String? {
        guard let value,
              range.length > 0,
              let stringRange = Range(range, in: value) else {
            return nil
        }

        let text = String(value[stringRange])
        return text.isEmpty ? nil : text
    }

    private func captureFocusedTextState() -> FocusedTextState? {
        guard let element = getFocusedTextElement() else { return nil }
        return captureFocusedTextState(for: element)
    }

    private func captureFocusedTextState(for element: AXUIElement) -> FocusedTextState? {
        if let focusedTextStateOverride {
            guard let snapshot = focusedTextStateOverride(element) else { return nil }
            return FocusedTextState(
                element: element,
                value: snapshot.value,
                selectedText: snapshot.selectedText,
                selectedRange: snapshot.selectedRange
            )
        }

        return FocusedTextState(
            element: element,
            value: stringAttribute(kAXValueAttribute as CFString, from: element),
            selectedText: stringAttribute(kAXSelectedTextAttribute as CFString, from: element),
            selectedRange: selectedRangeAttribute(from: element)
        )
    }

    private func stringAttribute(_ attribute: CFString, from element: AXUIElement) -> String? {
        var value: AnyObject?
        guard AXUIElementCopyAttributeValue(element, attribute, &value) == .success else { return nil }
        return value as? String
    }

    private func selectedRangeAttribute(from element: AXUIElement) -> NSRange? {
        var value: AnyObject?
        guard AXUIElementCopyAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, &value) == .success,
              let rangeValue = value else {
            return nil
        }

        return nsRange(from: rangeValue)
    }

    private func nsRange(from rangeValue: AnyObject) -> NSRange? {
        var range = CFRange()
        guard CFGetTypeID(rangeValue) == AXValueGetTypeID(),
              AXValueGetValue(rangeValue as! AXValue, .cfRange, &range) else {
            return nil
        }
        return NSRange(location: range.location, length: range.length)
    }

}
